### ISSUE TITLE
Doesn't seem to work with <1.3.0

### ISSUE THREAD

**Issue by T-vK** [pfalcon/esp-open-sdk#210]
These versions work just fine for me: `1.4.0`, `1.5.0`, `1.5.1`, `1.5.2`, `1.5.3`, `1.5.4`, `2.0.0`
1.2.0 and below won't successfully finish when running `make VENDOR_SDK=1.2.0`. I'm not entirely sure about 1.3.0 - but I think it doesn't work either.

Some errors I got for 1.2.0:

```
lwip/app/dhcpserver.c: In function 'wifi_softap_init_dhcps_lease':
lwip/app/dhcpserver.c:846:17: error: 'struct dhcps_lease' has no member named 'enable'
  if (dhcps_lease.enable == TRUE) {
                 ^
lwip/app/dhcpserver.c:852:15: error: 'struct dhcps_lease' has no member named 'enable'
    dhcps_lease.enable = FALSE;
               ^
lwip/app/dhcpserver.c:858:16: error: 'struct dhcps_lease' has no member named 'enable'
     dhcps_lease.enable = FALSE;
                ^
lwip/app/dhcpserver.c:863:17: error: 'struct dhcps_lease' has no member named 'enable'
  if (dhcps_lease.enable == FALSE) {
                 ^
lwip/app/dhcpserver.c: In function 'wifi_softap_set_dhcps_lease':
lwip/app/dhcpserver.c:961:11: error: 'struct dhcps_lease' has no member named 'enable'
  if(please->enable) {
           ^
lwip/app/dhcpserver.c:988:13: error: 'struct dhcps_lease' has no member named 'enable'
  dhcps_lease.enable = please->enable;
             ^
lwip/app/dhcpserver.c:988:29: error: 'struct dhcps_lease' has no member named 'enable'
  dhcps_lease.enable = please->enable;
                             ^
lwip/app/dhcpserver.c: In function 'wifi_softap_get_dhcps_lease':
lwip/app/dhcpserver.c:1012:17: error: 'struct dhcps_lease' has no member named 'enable'
  if (dhcps_lease.enable == FALSE){
                 ^
<builtin>: recipe for target 'lwip/app/dhcpserver.o' failed
make[1]: Leaving directory '/home/esp/esp-open-sdk/esp-open-lwip'
make[1]: *** [lwip/app/dhcpserver.o] Error 1
Makefile:338: recipe for target 'lwip' failed
make: *** [lwip] Error 2
```

**Comment by pfalcon** [comment]
Support for older versions is provided as is.
